development:
  clients:
    default:
      database: <%= ENV['MONGODB_DATABASE'] %>
      hosts:
        - <%= ENV['MONGODB_HOST'] %>
      options:
        user: "<%= ENV['MONGODB_CREDENTIALS'].try(:split, ':').try(:[], 0) %>"
        password: "<%= ENV['MONGODB_CREDENTIALS'].try(:split, ':').try(:[], 1) %>"
