# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

local:
  prs_context_id: <%= ENV["PRS_CONTEXT_ID"] %>
  prs_environment: <%= ENV["PRS_ENVIRONMENT"] %>
  prs_session_token: <%= ENV["PRS_SESSION_TOKEN"] %>
  prs_shared_secret: <%= ENV["PRS_SHARED_SECRET"] %>
  prs_url: <%= ENV["PRS_URL"] %>
  prs_zone_id: <%= ENV["PRS_ZONE_ID"] %>

development:
  prs_context_id: <%= ENV["PRS_CONTEXT_ID"] %>
  prs_environment: <%= ENV["PRS_ENVIRONMENT"] %>
  prs_session_token: <%= ENV["PRS_SESSION_TOKEN"] %>
  prs_shared_secret: <%= ENV["PRS_SHARED_SECRET"] %>
  prs_url: <%= ENV["PRS_URL"] %>
  prs_zone_id: <%= ENV["PRS_ZONE_ID"] %>

test:
  prs_context_id: <%= ENV["PRS_CONTEXT_ID"] %>
  prs_environment: <%= ENV["PRS_ENVIRONMENT"] %>
  prs_session_token: <%= ENV["PRS_SESSION_TOKEN"] %>
  prs_shared_secret: <%= ENV["PRS_SHARED_SECRET"] %>
  prs_url: <%= ENV["PRS_URL"] %>
  prs_zone_id: <%= ENV["PRS_ZONE_ID"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  prs_context_id: <%= ENV["PRS_CONTEXT_ID"] %>
  prs_environment: <%= ENV["PRS_ENVIRONMENT"] %>
  prs_session_token: <%= ENV["PRS_SESSION_TOKEN"] %>
  prs_shared_secret: <%= ENV["PRS_SHARED_SECRET"] %>
  prs_url: <%= ENV["PRS_URL"] %>
  prs_zone_id: <%= ENV["PRS_ZONE_ID"] %>
