# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00dd2882e78941644179fd1c8f3fa8ad567827b467df5c668b0ea31d6e73b8f60fa0a0fd2add161e577ddf231828204e767b40d90e7f186f19994afa3fe7a505
  prs_session_token: <%= ENV["PRS_SESSION_TOKEN"] %>
  prs_shared_secret: <%= ENV["PRS_SHARED_SECRET"] %>
  prs_url: https://srx-services-prs-dev.herokuapp.com
  prs_environment: DEV

test:
  secret_key_base: 22527491eeead900069ff0a1e79ee9a14881cd9aaa20fc7cae2909377c5ec8ce84810fe3647d64f7b67ee9152ef75124617990834809298e8700c6ce55a4ea66
  prs_session_token: <%= ENV["PRS_SESSION_TOKEN"] %>
  prs_shared_secret: <%= ENV["PRS_SHARED_SECRET"] %>
  prs_url: https://srx-services-prs-dev.herokuapp.com
  prs_environment: TEST

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  prs_session_token: <%= ENV["PRS_SESSION_TOKEN"] %>
  prs_shared_secret: <%= ENV["PRS_SHARED_SECRET"] %>
  prs_url: <%= ENV["PRS_URL"] %>
  prs_environment: <%= ENV["PRS_ENVIRONMENT"] %>
